version: "3.7"
services:
  {{ cookiecutter.project_slug }}:
    # bypass normal start by going directly as root in starting folder
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:development
    volumes:
      - ./src:/home/scu/src
      - ./docker/{%- if cookiecutter.docker_base.startswith("alpine") -%}alpine{%- elif cookiecutter.docker_base.startswith("python") -%}python{%- endif -%}:/home/scu/docker
      - ./service.cli:/home/scu/service.cli
