version: '3.7'
services:
  {{ cookiecutter.project_slug }}:
    image: local/${DOCKER_IMAGE_NAME}:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/{%- if cookiecutter.docker_base.startswith("alpine") -%}alpine{%- elif cookiecutter.docker_base.startswith("python") -%}python{%- endif -%}/Dockerfile
      target: production

