version: '3.7'
services:
  {{ cookiecutter.project_slug }}:
    image: ${DOCKER_REGISTRY}/simcore/services/{%- if cookiecutter.project_type == "computational" -%}comp{%- elif cookiecutter.project_type == "dynamic" -%}dynamic{%- endif -%}/{{ cookiecutter.project_name.lower().replace(' ', '-') }}:latest
    command: run
    build:
      context: ./
      dockerfile: src/Dockerfile
      target: production
    environment:
      - INPUT_FOLDER=/input/7848096d-20c2-4621-abcc-51c6ef9b0ecc
      - OUTPUT_FOLDER=/output/7848096d-20c2-4621-abcc-51c6ef9b0ecc
      - LOG_FOLDER=/log/7848096d-20c2-4621-abcc-51c6ef9b0ecc
    init: true
    volumes:
      # some defaults to test the service
      - ./validation/input:/input/7848096d-20c2-4621-abcc-51c6ef9b0ecc
      - ./tmp/output:/output/7848096d-20c2-4621-abcc-51c6ef9b0ecc
      - ./tmp/log:/log/7848096d-20c2-4621-abcc-51c6ef9b0ecc
