version: '3.7'
services:
  {{ cookiecutter.project_slug }}:
    # bypass normal start by going directly as root in starting folder
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${KERNEL_VERSION}-dev
    volumes:
      - ./src:/home/scu/src
      - ./docker:/home/scu/docker
      - ./service.cli:/home/scu/service.cli
