version: '3'
services:
  {{ cookiecutter.project_slug }}:
    image: ${DOCKER_REGISTRY}/simcore/services/{%- if cookiecutter.project_type == "computational" -%}comp{%- elif cookiecutter.project_type == "dynamic" -%}dynamic{%- endif -%}/{{ cookiecutter.project_name.lower().replace(' ', '-') }}:latest
    build:
      context: ./
      dockerfile: src/Dockerfile
      target: production
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: {{ cookiecutter.project_github_repo }}
        org.label-schema.vcs-ref: "${VCS_REF}"
