dist: bionic
language: python
addons:
  apt:
    packages:
      - python3
      - "python3-pip"
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install -r requirements.txt"
before_script:
  - python -V
  - python3 -V
  - pip -V
  - pip3 -V
  - docker --version
  - docker-compose --version
script:
  - pytest --cov=cookiecutter-osparc-service --durations=10 --cov-append --color=yes --cov-report=term-missing --cov-report=xml --cov-config=.coveragerc -vv tests
