os: linux
dist: bionic
language: python
addons:
  apt:
    packages:
      - python3
      - "python3-pip"
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - python -V
  - python3 -V
  - pip -V
  - pip3 -V
  - docker --version
  - docker-compose --version

script:
  # NOTE: travis uses some virtualenv. so here we do not call make devenv as in github actions.
  - pip install -r requirements.txt  
  - pytest --cov=cookiecutter-osparc-service --durations=10 --cov-append --color=yes --cov-report=term-missing --cov-report=xml --cov-config=.coveragerc -vv --basetemp=${PWD}/tmp tests
