image: itisfoundation/gitlab-runner-python-alpine:3.6
variables:
  # variables used for pytest: as gitlab-runner is itself running a docker, the mounted volume must be a named volume
  SC_CI_PYTEST_TMP_NAME: "gitlab_pytest_tmp"
  SC_CI_PYTEST_TMP: "/gitlab_pytest_tmp"
  SC_CI_TEST_IMAGE_PREFIX: $SC_CI_TESTING_REGISTRY/ci/$CI_PROJECT_NAME/$GITLAB_USER_LOGIN/$CI_COMMIT_REF_SLUG

# --------------------------------------------------------------------------------------------
# ------- {{ cookiecutter.project_slug }}
# --------------------------------------------------------------------------------------------
{{ cookiecutter.project_slug }}-build:
  stage: build
  except:
    - production
  script:
    - echo "$SC_CI_TESTING_REGISTRY_PASSWORD" | docker login -u "$SC_CI_TESTING_REGISTRY_USER" --password-stdin $SC_CI_TESTING_REGISTRY
    - cd models/{{ cookiecutter.project_slug }}
    - export DOCKER_REGISTRY=$SC_CI_STAGING_REGISTRY
    - make pull
    - export DOCKER_REGISTRY=$SC_CI_TEST_IMAGE_PREFIX
    - make build
    - make push

{{ cookiecutter.project_slug }}-unit-test:
  stage: test
  except:
    - production
  script:
    - pip install -r models/{{ cookiecutter.project_slug }}/tests/requirements.txt
    - cd models/{{ cookiecutter.project_slug }}
    - make unit-test
  artifacts:
    reports:
      junit:
        - models/{{ cookiecutter.project_slug }}/pytest_unittest.xml

{{ cookiecutter.project_slug }}-integration-test:
  stage: test
  except:
    - production
  script:
    - echo "$SC_CI_TESTING_REGISTRY_PASSWORD" | docker login -u "$SC_CI_TESTING_REGISTRY_USER" --password-stdin $SC_CI_TESTING_REGISTRY
    - pip install -r models/{{ cookiecutter.project_slug }}/tests/requirements.txt
    - cd models/{{ cookiecutter.project_slug }}
    - export DOCKER_REGISTRY=$SC_CI_TEST_IMAGE_PREFIX
    - make pull
    - make integration-test
  artifacts:
    reports:
      junit:
        - models/{{ cookiecutter.project_slug }}/pytest_integrationtest.xml

{{ cookiecutter.project_slug }}-staging:
  stage: deploy
  only:
    - master
  script:
    - echo "$SC_CI_TESTING_REGISTRY_PASSWORD" | docker login -u "$SC_CI_TESTING_REGISTRY_USER" --password-stdin $SC_CI_TESTING_REGISTRY
    - echo "SC_$CI_STAGING_REGISTRY_PASSWORD" | docker login -u "$SC_CI_STAGING_REGISTRY_USER" --password-stdin $SC_CI_STAGING_REGISTRY
    - cd models/{{ cookiecutter.project_slug }}
    - export DOCKER_REGISTRY=$SC_CI_TEST_IMAGE_PREFIX
    - make pull
    - docker tag $SC_CI_TEST_IMAGE_PREFIX/simcore/services/{%- if cookiecutter.project_type == "computational" -%}comp{%- elif cookiecutter.project_type == "dynamic" -%}dynamic{%- endif -%}/{{ cookiecutter.project_name.lower().replace(' ', '-') }} $SC_CI_STAGING_REGISTRY/simcore/services/{%- if cookiecutter.project_type == "computational" -%}comp{%- elif cookiecutter.project_type == "dynamic" -%}dynamic{%- endif -%}/{{ cookiecutter.project_name.lower().replace(' ', '-') }}
    - export DOCKER_REGISTRY=$SC_CI_STAGING_REGISTRY
    - make push

{{ cookiecutter.project_slug }}-production:
  stage: deploy
  only:
    - production
  script:
    - echo "$SC_CI_STAGING_REGISTRY_PASSWORD" | docker login -u "$SC_CI_STAGING_REGISTRY_USER" --password-stdin $SC_CI_STAGING_REGISTRY
    - echo "$SC_CI_PRODUCTION_REGISTRY_PASSWORD" | docker login -u "$SC_CI_PRODUCTION_REGISTRY_USER" --password-stdin $SC_CI_PRODUCTION_REGISTRY
    - cd models/{{ cookiecutter.project_slug }}
    - export DOCKER_REGISTRY=$SC_CI_STAGING_REGISTRY
    - make pull
    - docker tag $SC_CI_STAGING_REGISTRY/simcore/services/{%- if cookiecutter.project_type == "computational" -%}comp{%- elif cookiecutter.project_type == "dynamic" -%}dynamic{%- endif -%}/{{ cookiecutter.project_name.lower().replace(' ', '-') }} $SC_CI_PRODUCTION_REGISTRY/simcore/services/{%- if cookiecutter.project_type == "computational" -%}comp{%- elif cookiecutter.project_type == "dynamic" -%}dynamic{%- endif -%}/{{ cookiecutter.project_name.lower().replace(' ', '-') }}
    - export DOCKER_REGISTRY=$SC_CI_PRODUCTION_REGISTRY
    - make push-release
