version: "3.7"
services:
  {{ cookiecutter.project_slug }}:
    build:
      dockerfile: docker/{{ cookiecutter.docker_base.split(":")[0] }}/Dockerfile
      target: production
    # (only for testing)
    init: true
    environment:
      - INPUT_FOLDER=/input/7848096d-20c2-4621-abcc-51c6ef9b0ecc
      - OUTPUT_FOLDER=/output/7848096d-20c2-4621-abcc-51c6ef9b0ecc
    volumes:
      # some defaults to test the service
      - ${COMPOSE_INPUT_DIR}:/input/7848096d-20c2-4621-abcc-51c6ef9b0ecc
      - ${COMPOSE_OUTPUT_DIR}:/output/7848096d-20c2-4621-abcc-51c6ef9b0ecc
