name: Github-CI Push/PR

env:
  DOCKER_COMPOSE_VERSION: "1.25.3"
  DOCKER_BUILDX: "0.3.1"

on:
  push:
  pull_request:

jobs:
  cookie-cutter-osparc:
    name: testing cookie-cutter-osparc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        os: [ubuntu-18.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: setup docker
        run: |
          sudo ./ci/helpers/setup_docker_compose.bash
          ./ci/helpers/setup_docker_buildx.bash
      - name: setup python environment
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python }}
      - name: show versions
        run: ./ci/helpers/show_system_versions.bash
      - uses: actions/cache@v1
        name: getting cached data
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: set dev environs
        run: make devenv
      - name: test cookiecutter
        run: |
          source .venv/bin/activate
          pytest --cov=cookiecutter-osparc-service --durations=10 --cov-append --color=yes --cov-report=term-missing --cov-report=xml --cov-config=.coveragerc -vv tests
